version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web-app:
    build: ./web-app
    ports:
      - "5050:5000"
    volumes:
      - shared_data:/shared/uploads
    depends_on:
      - mongo

  ml-client:
    build: ./machine-learning-client
    ports:
      - "5001:5001"
    volumes:
      - shared_data:/shared/uploads
    depends_on:
      - mongo
    env_file:
      - ./machine-learning-client/.env

volumes:
  mongo_data:
  shared_data:
